:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= app-services-deploy-template
:numbered:

== Overview
Purpose of this project is to provide a skeleton ansible playbook that can be copied and modified to deploy an application to OpenShift.

This project is taken from the ansible wrapped to link:https://github.com/Emergency-Response-Demo/erdemo-operator[deploy the Red Hat Emergency Response Demo] to OpenShift.

For demonstration purposes, this skeleton deploys a link:https://github.com/hapifhir/hapi-fhir-jpaserver-starter[HAPI FHIR Server] and supporting PostgreSQL database to OpenShift.

== Pre-reqs 

. `oc` utility
. `ansible-playbook` utility

== Usage

. Clone this project: 

. Review key files and directories: 

.. link:playbooks/install.yml[playbooks/install.yml]
+
Serves as playbook that invokes all ansible roles in project.
+
Notice that playbook can optionally be invoked with a variable of *ACTION=install* or *ACTION=uninstall*  

.. link:playbooks/group_vars/all.yml[playbooks/group_vars/all.yml]
+
Defines global scoped variables.

. link:roles[roles]
+
Director containing all project roles.

.. fhirserver
+
Example role that deploys PostgreSQL database and HAPI FHIR server

.. openshift_domain
+
Optional role that sets the following variable with the domain name of the OpenShift cluster (ie:  apps.234.234-DEN.opentlc.com) :  ocp_domain_host

.. openshift_project
+
Optional role that creates an project namespace (if it doesn't already exist)

. link:resources[resources]
+
Supporting files used by the project ansible roles

. Using the version of the openshift command line utility that correspondes to the version of your openshift cluster, log into the OpenShift cluster.

. Execute the following to install: 
+
-----
$ ansible-playbook playbooks/install.yml \
    -e ACTION=install \
    -e deploy_from=image
-----

. Execute the following to uninstall:
+
-----
$ ansible-playbook playbooks/install.yml \
    -e ACTION=uninstall
-----

